"""Phase 3 evidence subpackage."""
from open_deep_research.evidence.eu_dao import (
    ClaimDAO,
    EuDAO,
    RunCheckpointDAO,
    host_of,
)
from open_deep_research.evidence.independence import (
    PRIMARY_DOMAINS,
    SECONDARY_DOMAINS,
    UGC_DOMAINS,
    classify_source_tier,
    grade_claim,
    independent_source_count,
    primary_source_count,
    registrable_domain,
    upgrade_source_tier,
)
from open_deep_research.evidence.llm_entailment import (
    DEFAULT_BATCH_SIZE,
    verify_entailment_batch,
    verify_entailment_batch_sync,
)
from open_deep_research.evidence.llm_extractor import (
    extract_from_content_with_llm,
    extract_from_search_results_with_llm,
)
from open_deep_research.evidence.merge import (
    MERGE_COSINE,
    NUMERIC_TOL,
    ClaimDraft,
    build_claim_drafts,
    merge_units,
    same_unit,
)
from open_deep_research.evidence.checkpoint import (
    STAGES,
    get_resume_point,
    is_run_complete,
    list_completed_stages,
    list_failed_stages,
    mark_stage_done,
    mark_stage_failed,
    mark_stage_running,
    reset_run,
)
from open_deep_research.evidence.dag import (
    DAG,
    DAGNode,
    DAGValidationError,
    NodeQuota,
    batch_dag_for_dimensions,
    dag_to_stages,
    default_pipeline_dag,
    topo_sort,
    validate_dag,
)
from open_deep_research.evidence.grade_retro import (
    DEFAULT_D_THRESHOLD,
    DEFAULT_MAX_RETRIES,
    DEFAULT_RETRY_STAGES,
    detect_grade_d_pct,
    retro_summary,
    run_with_retro_loop,
    should_retry,
)
from open_deep_research.evidence.job_runner import (
    ResearchJob,
    StageAlreadyDone,
)
from open_deep_research.evidence.observability import (
    flush_observability,
    observability_status,
    stage_trace,
)
from open_deep_research.evidence.per_dim_retro import run_with_per_dim_retro
from open_deep_research.evidence.pipeline import build_claims_from_eus
from open_deep_research.evidence.report import (
    ClaimStats,
    Failure,
    ReportResult,
    ReportSection,
    is_report_success,
)
from open_deep_research.evidence.schema import (
    ClaimV2,
    ClaimType,
    EvidenceUnitV2,
    Grade,
    SourceTier,
    Verdict,
)
from open_deep_research.evidence.verify import (
    ENTAILMENT_PROMPT,
    EntailmentBatchResult,
    EntailmentResult,
    GateStats,
    _normalize,
    _numbers,
    _render_entailment_items,
    has_numeric_drift,
    parse_entailment_response,
    run_gate1_span,
    run_gate2_numeric_drift,
    verify_span,
)

__all__ = [
    "ClaimDAO",
    "ClaimDraft",
    "ClaimV2",
    "ClaimType",
    "DEFAULT_BATCH_SIZE",
    "ENTAILMENT_PROMPT",
    "EntailmentBatchResult",
    "EntailmentResult",
    "DAG",
    "DAGNode",
    "DAGValidationError",
    "EuDAO",
    "EvidenceUnitV2",
    "Failure",
    "GateStats",
    "Grade",
    "MERGE_COSINE",
    "NUMERIC_TOL",
    "NodeQuota",
    "PRIMARY_DOMAINS",
    "ReportResult",
    "ReportSection",
    "ResearchJob",
    "DEFAULT_D_THRESHOLD",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_RETRY_STAGES",
    "RunCheckpointDAO",
    "SECONDARY_DOMAINS",
    "STAGES",
    "SourceTier",
    "StageAlreadyDone",
    "UGC_DOMAINS",
    "Verdict",
    "_normalize",
    "_numbers",
    "_render_entailment_items",
    "batch_dag_for_dimensions",
    "build_claim_drafts",
    "build_claims_from_eus",
    "classify_source_tier",
    "dag_to_stages",
    "default_pipeline_dag",
    "detect_grade_d_pct",
    "extract_from_content_with_llm",
    "extract_from_search_results_with_llm",
    "flush_observability",
    "get_resume_point",
    "grade_claim",
    "has_numeric_drift",
    "host_of",
    "independent_source_count",
    "is_report_success",
    "is_run_complete",
    "list_completed_stages",
    "list_failed_stages",
    "mark_stage_done",
    "mark_stage_failed",
    "mark_stage_running",
    "merge_units",
    "observability_status",
    "parse_entailment_response",
    "primary_source_count",
    "registrable_domain",
    "reset_run",
    "retro_summary",
    "run_gate1_span",
    "run_gate2_numeric_drift",
    "run_with_per_dim_retro",
    "run_with_retro_loop",
    "same_unit",
    "should_retry",
    "stage_trace",
    "topo_sort",
    "upgrade_source_tier",
    "validate_dag",
    "verify_entailment_batch",
    "verify_entailment_batch_sync",
    "verify_span",
]  # noqa: E501