"""Phase 3 evidence subpackage."""
from open_deep_research.evidence.eu_dao import (
    ClaimDAO,
    EuDAO,
    RunCheckpointDAO,
    host_of,
)
from open_deep_research.evidence.independence import (
    PRIMARY_DOMAINS,
    SECONDARY_DOMAINS,
    UGC_DOMAINS,
    classify_source_tier,
    grade_claim,
    independent_source_count,
    primary_source_count,
    registrable_domain,
    upgrade_source_tier,
)
from open_deep_research.evidence.llm_entailment import (
    DEFAULT_BATCH_SIZE,
    verify_entailment_batch,
    verify_entailment_batch_sync,
)
from open_deep_research.evidence.llm_extractor import (
    extract_from_content_with_llm,
    extract_from_search_results_with_llm,
)
from open_deep_research.evidence.merge import (
    MERGE_COSINE,
    NUMERIC_TOL,
    ClaimDraft,
    build_claim_drafts,
    merge_units,
    same_unit,
)
from open_deep_research.evidence.pipeline import build_claims_from_eus
from open_deep_research.evidence.schema import (
    ClaimV2,
    ClaimType,
    EvidenceUnitV2,
    Grade,
    SourceTier,
    Verdict,
)
from open_deep_research.evidence.verify import (
    ENTAILMENT_PROMPT,
    EntailmentBatchResult,
    EntailmentResult,
    GateStats,
    _normalize,
    _numbers,
    _render_entailment_items,
    has_numeric_drift,
    parse_entailment_response,
    run_gate1_span,
    run_gate2_numeric_drift,
    verify_span,
)

__all__ = [
    "ClaimDAO",
    "ClaimDraft",
    "ClaimV2",
    "ClaimType",
    "DEFAULT_BATCH_SIZE",
    "ENTAILMENT_PROMPT",
    "EntailmentBatchResult",
    "EntailmentResult",
    "EuDAO",
    "EvidenceUnitV2",
    "GateStats",
    "Grade",
    "MERGE_COSINE",
    "NUMERIC_TOL",
    "PRIMARY_DOMAINS",
    "RunCheckpointDAO",
    "SECONDARY_DOMAINS",
    "SourceTier",
    "UGC_DOMAINS",
    "Verdict",
    "_normalize",
    "_numbers",
    "_render_entailment_items",
    "build_claim_drafts",
    "build_claims_from_eus",
    "classify_source_tier",
    "extract_from_content_with_llm",
    "extract_from_search_results_with_llm",
    "grade_claim",
    "has_numeric_drift",
    "host_of",
    "independent_source_count",
    "merge_units",
    "parse_entailment_response",
    "primary_source_count",
    "registrable_domain",
    "run_gate1_span",
    "run_gate2_numeric_drift",
    "same_unit",
    "upgrade_source_tier",
    "verify_entailment_batch",
    "verify_entailment_batch_sync",
    "verify_span",
]